-- SkillStreak proposed PostgreSQL schema
--
-- This is executable reference DDL for the draft in
-- docs/proposed-schema-erd.md. Production Django schema changes must be
-- represented by reviewed Django migrations; do not apply this file directly
-- to a production database.
--
-- Preconditions:
--   * Django's configured user table is accounts_user.
--   * accounts_user.id is a bigint primary key.
-- If a custom Django user model is adopted, generate the foreign keys from
-- settings.AUTH_USER_MODEL in Django migrations instead of editing this file.

BEGIN;

CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE user_preferences (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL UNIQUE
        REFERENCES accounts_user (id) ON DELETE CASCADE,
    timezone varchar(63) NOT NULL DEFAULT 'UTC'
);

CREATE TABLE skills (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id bigint REFERENCES skills (id) ON DELETE RESTRICT,
    created_by_id bigint REFERENCES accounts_user (id) ON DELETE SET NULL,
    slug varchar(64) NOT NULL UNIQUE,
    name varchar(100) NOT NULL,
    description text NOT NULL DEFAULT '',
    visibility varchar(16) NOT NULL DEFAULT 'SYSTEM',
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT skills_nonempty_slug CHECK (btrim(slug) <> ''),
    CONSTRAINT skills_nonempty_name CHECK (btrim(name) <> ''),
    CONSTRAINT skills_visibility_check
        CHECK (visibility IN ('SYSTEM', 'PUBLIC', 'PRIVATE'))
);

CREATE TABLE metric_definitions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_id bigint NOT NULL REFERENCES skills (id) ON DELETE RESTRICT,
    key varchar(64) NOT NULL,
    label varchar(100) NOT NULL,
    value_type varchar(16) NOT NULL,
    canonical_unit varchar(32),
    aggregation varchar(16) NOT NULL DEFAULT 'LATEST',
    minimum_value numeric(14, 3),
    maximum_value numeric(14, 3),
    allows_multiple_values boolean NOT NULL DEFAULT false,
    display_order smallint NOT NULL DEFAULT 0,
    is_active boolean NOT NULL DEFAULT true,

    CONSTRAINT metric_definitions_skill_key_unique UNIQUE (skill_id, key),
    CONSTRAINT metric_definitions_nonempty_key CHECK (btrim(key) <> ''),
    CONSTRAINT metric_definitions_nonempty_label CHECK (btrim(label) <> ''),
    CONSTRAINT metric_definitions_value_type_check
        CHECK (value_type IN ('NUMBER', 'TEXT', 'BOOLEAN')),
    CONSTRAINT metric_definitions_aggregation_check
        CHECK (aggregation IN ('LATEST', 'SUM', 'MAX', 'MIN', 'AVERAGE')),
    CONSTRAINT metric_definitions_range_check
        CHECK (
            minimum_value IS NULL
            OR maximum_value IS NULL
            OR minimum_value <= maximum_value
        ),
    CONSTRAINT metric_definitions_display_order_check CHECK (display_order >= 0)
);

CREATE TABLE user_skills (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES accounts_user (id) ON DELETE CASCADE,
    skill_id bigint NOT NULL REFERENCES skills (id) ON DELETE RESTRICT,
    started_on date NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT user_skills_user_skill_unique UNIQUE (user_id, skill_id)
);

CREATE INDEX user_skills_skill_active_idx
    ON user_skills (skill_id, is_active);

CREATE TABLE daily_completions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_skill_id bigint NOT NULL
        REFERENCES user_skills (id) ON DELETE CASCADE,
    completed_on date NOT NULL,
    recorded_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT daily_completions_user_skill_date_unique
        UNIQUE (user_skill_id, completed_on)
);

CREATE TABLE user_skill_schedules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_skill_id bigint NOT NULL
        REFERENCES user_skills (id) ON DELETE CASCADE,
    rule_type varchar(16) NOT NULL,
    effective_from date NOT NULL,
    effective_through date,
    interval_days smallint,
    target_days_per_week smallint,
    week_starts_on smallint,
    short_month_policy varchar(16),

    CONSTRAINT user_skill_schedules_dates_check
        CHECK (effective_through IS NULL OR effective_through >= effective_from),
    CONSTRAINT user_skill_schedules_rule_check CHECK (
        (rule_type = 'DAILY'
            AND interval_days IS NULL
            AND target_days_per_week IS NULL
            AND week_starts_on IS NULL
            AND short_month_policy IS NULL)
        OR (rule_type = 'EVERY_N_DAYS'
            AND interval_days >= 2
            AND target_days_per_week IS NULL
            AND week_starts_on IS NULL
            AND short_month_policy IS NULL)
        OR (rule_type = 'DAYS_PER_WEEK'
            AND interval_days IS NULL
            AND target_days_per_week BETWEEN 1 AND 7
            AND week_starts_on BETWEEN 1 AND 7
            AND short_month_policy IS NULL)
        OR (rule_type = 'DAYS_OF_WEEK'
            AND interval_days IS NULL
            AND target_days_per_week IS NULL
            AND week_starts_on IS NULL
            AND short_month_policy IS NULL)
        OR (rule_type = 'DAYS_OF_MONTH'
            AND interval_days IS NULL
            AND target_days_per_week IS NULL
            AND week_starts_on IS NULL
            AND short_month_policy IN ('SKIP', 'LAST_DAY'))
    ),
    CONSTRAINT user_skill_schedules_no_date_overlap
        EXCLUDE USING gist (
            user_skill_id WITH =,
            daterange(
                effective_from,
                COALESCE(effective_through + 1, 'infinity'::date),
                '[)'
            ) WITH &&
        )
);

CREATE TABLE schedule_weekdays (
    schedule_id bigint NOT NULL
        REFERENCES user_skill_schedules (id) ON DELETE CASCADE,
    weekday smallint NOT NULL,

    CONSTRAINT schedule_weekdays_primary_key PRIMARY KEY (schedule_id, weekday),
    CONSTRAINT schedule_weekdays_weekday_check CHECK (weekday BETWEEN 1 AND 7)
);

CREATE TABLE schedule_month_days (
    schedule_id bigint NOT NULL
        REFERENCES user_skill_schedules (id) ON DELETE CASCADE,
    day_of_month smallint NOT NULL,

    CONSTRAINT schedule_month_days_primary_key
        PRIMARY KEY (schedule_id, day_of_month),
    CONSTRAINT schedule_month_days_day_check CHECK (day_of_month BETWEEN 1 AND 31)
);

CREATE TABLE metric_measurements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    daily_completion_id bigint NOT NULL
        REFERENCES daily_completions (id) ON DELETE CASCADE,
    metric_definition_id bigint NOT NULL
        REFERENCES metric_definitions (id) ON DELETE RESTRICT,
    series_index smallint NOT NULL DEFAULT 0,
    numeric_value numeric(14, 3),
    text_value text,
    boolean_value boolean,
    recorded_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT metric_measurements_completion_metric_series_unique
        UNIQUE (daily_completion_id, metric_definition_id, series_index),
    CONSTRAINT metric_measurements_series_index_check CHECK (series_index >= 0),
    CONSTRAINT metric_measurements_exactly_one_value_check CHECK (
        (CASE WHEN numeric_value IS NULL THEN 0 ELSE 1 END)
        + (CASE WHEN text_value IS NULL THEN 0 ELSE 1 END)
        + (CASE WHEN boolean_value IS NULL THEN 0 ELSE 1 END) = 1
    )
);

CREATE INDEX metric_measurements_definition_idx
    ON metric_measurements (metric_definition_id);

-- Django must validate the following relationship-dependent business rules:
--   * A completion belongs to an active user_skill and is within its dates.
--   * A measurement definition belongs to the completed skill and its value
--     matches value_type and configured numeric bounds.
--   * DAYS_OF_WEEK schedules have weekday rows only; DAYS_OF_MONTH schedules
--     have month-day rows only; each has at least one selected day.
--   * A streak is derived from user_skill_schedules and daily_completions.

COMMIT;
