# Generated by Django 5.2.17 on 2026-10-05 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("SYSTEM", "System"),
                            ("PUBLIC", "Public"),
                            ("PRIVATE", "Private"),
                        ],
                        default="SYSTEM",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="tracking.skill",
                    ),
                ),
            ],
            options={
                "db_table": "skills",
            },
        ),
        migrations.CreateModel(
            name="MetricDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=64)),
                ("label", models.CharField(max_length=100)),
                (
                    "value_type",
                    models.CharField(
                        choices=[("NUMBER", "Number"), ("TEXT", "Text"), ("BOOLEAN", "Boolean")],
                        max_length=16,
                    ),
                ),
                ("canonical_unit", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "aggregation",
                    models.CharField(
                        choices=[
                            ("LATEST", "Latest"),
                            ("SUM", "Sum"),
                            ("MAX", "Max"),
                            ("MIN", "Min"),
                            ("AVERAGE", "Average"),
                        ],
                        default="LATEST",
                        max_length=16,
                    ),
                ),
                (
                    "minimum_value",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
                ),
                (
                    "maximum_value",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
                ),
                ("allows_multiple_values", models.BooleanField(default=False)),
                ("display_order", models.SmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="tracking.skill"
                    ),
                ),
            ],
            options={
                "db_table": "metric_definitions",
            },
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("timezone", models.CharField(default="UTC", max_length=63)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "user_preferences",
            },
        ),
        migrations.CreateModel(
            name="UserSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("started_on", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="tracking.skill"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "user_skills",
            },
        ),
        migrations.CreateModel(
            name="DailyCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("completed_on", models.DateField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user_skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tracking.userskill"
                    ),
                ),
            ],
            options={
                "db_table": "daily_completions",
            },
        ),
        migrations.CreateModel(
            name="UserSkillSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("EVERY_N_DAYS", "Every N Days"),
                            ("DAYS_PER_WEEK", "Days Per Week"),
                            ("DAYS_OF_WEEK", "Days Of Week"),
                            ("DAYS_OF_MONTH", "Days Of Month"),
                        ],
                        max_length=16,
                    ),
                ),
                ("effective_from", models.DateField()),
                ("effective_through", models.DateField(blank=True, null=True)),
                ("interval_days", models.SmallIntegerField(blank=True, null=True)),
                ("target_days_per_week", models.SmallIntegerField(blank=True, null=True)),
                ("week_starts_on", models.SmallIntegerField(blank=True, null=True)),
                ("short_month_policy", models.CharField(blank=True, max_length=16, null=True)),
                (
                    "user_skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tracking.userskill"
                    ),
                ),
            ],
            options={
                "db_table": "user_skill_schedules",
            },
        ),
        migrations.CreateModel(
            name="ScheduleWeekday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("weekday", models.SmallIntegerField()),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tracking.userskillschedule"
                    ),
                ),
            ],
            options={
                "db_table": "schedule_weekdays",
            },
        ),
        migrations.CreateModel(
            name="ScheduleMonthDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("day_of_month", models.SmallIntegerField()),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tracking.userskillschedule"
                    ),
                ),
            ],
            options={
                "db_table": "schedule_month_days",
            },
        ),
        migrations.CreateModel(
            name="MetricMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("series_index", models.SmallIntegerField(default=0)),
                (
                    "numeric_value",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
                ),
                ("text_value", models.TextField(blank=True, null=True)),
                ("boolean_value", models.BooleanField(blank=True, null=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "daily_completion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tracking.dailycompletion"
                    ),
                ),
                (
                    "metric_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="tracking.metricdefinition"
                    ),
                ),
            ],
            options={
                "db_table": "metric_measurements",
                "indexes": [
                    models.Index(fields=["metric_definition"], name="metric_measurement_def_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("daily_completion", "metric_definition", "series_index"),
                        name="metric_measurements_completion_metric_series_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("series_index__gte", 0)),
                        name="metric_measurements_series_index_check",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="skill",
            constraint=models.CheckConstraint(
                condition=models.Q(("slug", ""), _negated=True), name="skills_nonempty_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="skill",
            constraint=models.CheckConstraint(
                condition=models.Q(("name", ""), _negated=True), name="skills_nonempty_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="metricdefinition",
            constraint=models.UniqueConstraint(
                fields=("skill", "key"), name="metric_definitions_skill_key_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="metricdefinition",
            constraint=models.CheckConstraint(
                condition=models.Q(("display_order__gte", 0)),
                name="metric_definitions_display_order_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="metricdefinition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("minimum_value__isnull", True),
                    ("maximum_value__isnull", True),
                    ("minimum_value__lte", models.F("maximum_value")),
                    _connector="OR",
                ),
                name="metric_definitions_range_check",
            ),
        ),
        migrations.AddIndex(
            model_name="userskill",
            index=models.Index(fields=["skill", "is_active"], name="user_skills_skill_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="userskill",
            constraint=models.UniqueConstraint(
                fields=("user", "skill"), name="user_skills_user_skill_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="dailycompletion",
            constraint=models.UniqueConstraint(
                fields=("user_skill", "completed_on"),
                name="daily_completions_user_skill_date_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="userskillschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_through__isnull", True),
                    ("effective_through__gte", models.F("effective_from")),
                    _connector="OR",
                ),
                name="user_skill_schedules_dates_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduleweekday",
            constraint=models.UniqueConstraint(
                fields=("schedule", "weekday"), name="schedule_weekdays_primary_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduleweekday",
            constraint=models.CheckConstraint(
                condition=models.Q(("weekday__gte", 1), ("weekday__lte", 7)),
                name="schedule_weekdays_weekday_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulemonthday",
            constraint=models.UniqueConstraint(
                fields=("schedule", "day_of_month"), name="schedule_month_days_primary_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulemonthday",
            constraint=models.CheckConstraint(
                condition=models.Q(("day_of_month__gte", 1), ("day_of_month__lte", 31)),
                name="schedule_month_days_day_check",
            ),
        ),
    ]
