# Generated by Django 5.2.17 on 2026-10-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="metricdefinition",
            constraint=models.CheckConstraint(
                condition=models.Q(("key", ""), _negated=True),
                name="metric_definitions_nonempty_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="metricdefinition",
            constraint=models.CheckConstraint(
                condition=models.Q(("label", ""), _negated=True),
                name="metric_definitions_nonempty_label",
            ),
        ),
        migrations.AddConstraint(
            model_name="metricmeasurement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("boolean_value__isnull", True),
                        ("numeric_value__isnull", False),
                        ("text_value__isnull", True),
                    ),
                    models.Q(
                        ("boolean_value__isnull", True),
                        ("numeric_value__isnull", True),
                        ("text_value__isnull", False),
                    ),
                    models.Q(
                        ("boolean_value__isnull", False),
                        ("numeric_value__isnull", True),
                        ("text_value__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="metric_measurements_exactly_one_value_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="userskillschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("interval_days__isnull", True),
                        ("rule_type", "DAILY"),
                        ("short_month_policy__isnull", True),
                        ("target_days_per_week__isnull", True),
                        ("week_starts_on__isnull", True),
                    ),
                    models.Q(
                        ("interval_days__gte", 2),
                        ("rule_type", "EVERY_N_DAYS"),
                        ("short_month_policy__isnull", True),
                        ("target_days_per_week__isnull", True),
                        ("week_starts_on__isnull", True),
                    ),
                    models.Q(
                        ("interval_days__isnull", True),
                        ("rule_type", "DAYS_PER_WEEK"),
                        ("short_month_policy__isnull", True),
                        ("target_days_per_week__gte", 1),
                        ("target_days_per_week__lte", 7),
                        ("week_starts_on__gte", 1),
                        ("week_starts_on__lte", 7),
                    ),
                    models.Q(
                        ("interval_days__isnull", True),
                        ("rule_type", "DAYS_OF_WEEK"),
                        ("short_month_policy__isnull", True),
                        ("target_days_per_week__isnull", True),
                        ("week_starts_on__isnull", True),
                    ),
                    models.Q(
                        ("interval_days__isnull", True),
                        ("rule_type", "DAYS_OF_MONTH"),
                        ("short_month_policy__in", ["SKIP", "LAST_DAY"]),
                        ("target_days_per_week__isnull", True),
                        ("week_starts_on__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="user_skill_schedules_rule_check",
            ),
        ),
    ]
